insert into juzgado (id_juzgado, nombre, apellido, direccion, telefono, correo) values (1, 'Rodrigo', 'González', 'Calle Falsa 123', '+86 605 954 7229', 'pkernaghan0@sourceforge.net');
insert into juzgado (id_juzgado, nombre, apellido, direccion, telefono, correo) values (2, 'Pilar', 'Rodríguez', 'Avenida Rivadavia 456', '+86 723 162 3391', 'spetyankin1@netlog.com');
insert into juzgado (id_juzgado, nombre, apellido, direccion, telefono, correo) values (3, 'Mia', 'Gómez', 'Calle San Martín 789', '+98 102 189 4960', 'hlukash2@hhs.gov');
insert into juzgado (id_juzgado, nombre, apellido, direccion, telefono, correo) values (4, 'Mia', 'Fernández', 'Pasaje Belgrano 101', '+976 488 674 1122', 'hrandle3@networksolutions.com');
insert into juzgado (id_juzgado, nombre, apellido, direccion, telefono, correo) values (5, 'Mariana', 'López', 'Avenida 9 de Julio 202', '+48 173 520 8024', 'dgrime4@columbia.edu');
insert into juzgado (id_juzgado, nombre, apellido, direccion, telefono, correo) values (6, 'Mateo', 'Díaz', 'Calle Sarmiento 303', '+62 402 820 8136', 'hscoggins5@cnbc.com');
insert into juzgado (id_juzgado, nombre, apellido, direccion, telefono, correo) values (7, 'Martina', 'Martínez', 'Pasaje Mitre 404', '+386 301 698 8501', 'mjansema6@adobe.com');
insert into juzgado (id_juzgado, nombre, apellido, direccion, telefono, correo) values (8, 'Julia', 'Pérez', 'Avenida Libertador 505', '+7 940 939 6130', 'lhadenton7@netlog.com');
insert into juzgado (id_juzgado, nombre, apellido, direccion, telefono, correo) values (9, 'Isabella', 'García', 'Calle Alvear 606', '+62 142 425 2326', 'rsimonnin8@nhs.uk');
insert into juzgado (id_juzgado, nombre, apellido, direccion, telefono, correo) values (10, 'Silvina', 'Sánchez', 'Pasaje Dorrego 707', '+62 207 735 1643', 'jabbot9@globo.com');
insert into juzgado (id_juzgado, nombre, apellido, direccion, telefono, correo) values (11, 'Sofia', 'Romero', 'Avenida Corrientes 808', '+86 657 608 4422', 'ggouldebya@utexas.edu');
insert into juzgado (id_juzgado, nombre, apellido, direccion, telefono, correo) values (12, 'Benjamin', 'Torres', 'Calle Pueyrredón 909', '+46 576 918 6407', 'hwealdb@usatoday.com');
insert into juzgado (id_juzgado, nombre, apellido, direccion, telefono, correo) values (13, 'Roberto', 'Suárez', 'Pasaje Lavalle 1010', '+354 140 253 8485', 'jbalshawc@posterous.com');
insert into juzgado (id_juzgado, nombre, apellido, direccion, telefono, correo) values (14, 'Sebastian', 'Álvarez', 'Avenida Santa Fe 1111', '+63 604 710 4740', 'amerrilld@about.me');
insert into juzgado (id_juzgado, nombre, apellido, direccion, telefono, correo) values (15, 'Catalina', 'Ramírez', 'Calle Florida 1212', '+55 979 882 6989', 'cpurslowe@economist.com');
insert into juzgado (id_juzgado, nombre, apellido, direccion, telefono, correo) values (16, 'Franco', 'Flores', 'Pasaje Reconquista 1313', '+976 247 222 9074', 'csamsinf@sbwire.com');
insert into juzgado (id_juzgado, nombre, apellido, direccion, telefono, correo) values (17, 'Nicolas', 'Benítez', 'Avenida Mayo 1414', '+55 490 700 9733', 'ychurchillg@bloglovin.com');
insert into juzgado (id_juzgado, nombre, apellido, direccion, telefono, correo) values (18, 'Martin', 'Acosta', 'Calle Córdoba 1515', '+504 862 526 8792', 'tdennickh@youtu.be');
insert into juzgado (id_juzgado, nombre, apellido, direccion, telefono, correo) values (19, 'Delfina', 'Medina', 'Pasaje Callao 1616', '+86 200 226 7901', 'ssteeni@fc2.com');
insert into juzgado (id_juzgado, nombre, apellido, direccion, telefono, correo) values (20, 'Abril', 'Herrera', 'Avenida Pellegrini 1717', '+351 291 443 8831', 'baptedj@themeforest.net');
